[package]
name = "gr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.9"
rayon = "1.5.0"
# reqwest = {version = "0.11", features = ["blocking", "json"]}
ureq = { version = "2.6.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
lazy_static = "1.4"
regex = "1.5"
sha2 = "0.10.2"
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
console = "0.15.7"
clap = "4.3"
open = "5.0.0"
thiserror = "1.0.40"
anyhow = "1.0.71"

[dev_dependencies]
# disable basic-cookies from httpmock - not needed
httpmock = { version = "0.6", default_features = false }
